create extension if not exists pgcrypto;

create type usuario_tipo as enum ('garcom', 'gestor', 'admin');
create type mesa_status as enum ('disponivel', 'ocupada', 'manutencao', 'esperando_pagamento');
create type produto_categoria as enum ('prato', 'bebida', 'extra');
create type comanda_status as enum ('pendente', 'em_preparo', 'pronto', 'pago', 'esperando_pagamento');

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  senha text not null,
  tipo usuario_tipo not null,
  created_at timestamptz not null default now()
);

create table if not exists mesas (
  id bigint generated by default as identity primary key,
  numero integer not null unique,
  status mesa_status not null default 'disponivel',
  created_at timestamptz not null default now()
);

create table if not exists produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  preco numeric(10,2) not null check (preco >= 0),
  categoria produto_categoria not null,
  descricao text,
  disponivel boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists comandas (
  id bigint generated by default as identity primary key,
  mesa_id bigint not null references mesas(id) on delete restrict,
  garcom_id bigint not null references usuarios(id) on delete restrict,
  status comanda_status not null default 'pendente',
  total numeric(10,2) not null default 0,
  numero_comanda text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists itens_comanda (
  id bigint generated by default as identity primary key,
  comanda_id bigint not null references comandas(id) on delete cascade,
  produto_id bigint not null references produtos(id) on delete restrict,
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10,2) not null check (preco_unitario >= 0),
  subtotal numeric(10,2) generated always as (quantidade * preco_unitario) stored,
  created_at timestamptz not null default now()
);

create table if not exists caixa_diario (
  id bigint generated by default as identity primary key,
  data date not null unique,
  valor_abertura numeric(10,2) not null default 0,
  valor_fechamento numeric(10,2),
  total_vendas numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_comandas_mesa_ativa
on comandas(mesa_id)
where status <> 'pago';

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_comandas_updated_at
before update on comandas
for each row execute function set_updated_at();

create trigger trg_caixa_updated_at
before update on caixa_diario
for each row execute function set_updated_at();

create or replace function recalcular_total_comanda()
returns trigger as $$
declare
  alvo bigint;
begin
  alvo := coalesce(new.comanda_id, old.comanda_id);

  update comandas
  set total = coalesce((
    select sum(subtotal)
    from itens_comanda
    where comanda_id = alvo
  ), 0)
  where id = alvo;

  return null;
end;
$$ language plpgsql;

create trigger trg_itens_recalcular_total
after insert or update or delete on itens_comanda
for each row execute function recalcular_total_comanda();

create or replace function atualizar_status_mesa_por_comanda()
returns trigger as $$
begin
  if tg_op = 'UPDATE' and old.status = new.status then
    return new;
  end if;

  if new.status = 'pago' then
    update mesas set status = 'disponivel' where id = new.mesa_id;

    insert into caixa_diario (data, total_vendas)
    values (current_date, new.total)
    on conflict (data)
    do update set
      total_vendas = caixa_diario.total_vendas + excluded.total_vendas,
      updated_at = now();
  elsif new.status = 'esperando_pagamento' then
    update mesas set status = 'esperando_pagamento' where id = new.mesa_id;
  else
    update mesas set status = 'ocupada' where id = new.mesa_id;
  end if;

  return new;
end;
$$ language plpgsql;

create trigger trg_comanda_status_mesa_insert
after insert on comandas
for each row execute function atualizar_status_mesa_por_comanda();

create trigger trg_comanda_status_mesa_update
after update of status on comandas
for each row execute function atualizar_status_mesa_por_comanda();

insert into usuarios (nome, email, senha, tipo) values
('Admin Sistema', 'admin@restaurante.com', '$2a$10$CwTycUXWue0Thq9StjUM0uJ8eH8zzjJgdu17I8AHdcqQy3orxnC0i', 'admin'),
('Joao Garcom', 'joao@restaurante.com', '$2a$10$CwTycUXWue0Thq9StjUM0uJ8eH8zzjJgdu17I8AHdcqQy3orxnC0i', 'garcom'),
('Maria Gestora', 'maria@restaurante.com', '$2a$10$CwTycUXWue0Thq9StjUM0uJ8eH8zzjJgdu17I8AHdcqQy3orxnC0i', 'gestor')
on conflict (email) do nothing;

insert into mesas (numero, status)
select n, 'disponivel'::mesa_status
from generate_series(1, 8) as n
on conflict (numero) do nothing;

insert into produtos (nome, preco, categoria, descricao) values
('Arroz com Feijao', 25.90, 'prato', 'Prato tradicional da casa'),
('Bife Acebolado', 35.90, 'prato', 'Bife grelhado com cebolas douradas'),
('Frango Assado', 32.90, 'prato', 'Frango assado com acompanhamentos'),
('Macarronada', 28.90, 'prato', 'Massa ao molho da casa'),
('Salada Completa', 22.90, 'prato', 'Folhas, legumes e molho especial'),
('Omelete', 18.90, 'prato', 'Omelete recheado'),
('File de Peixe', 42.90, 'prato', 'Peixe grelhado com acompanhamentos'),
('Strogonoff', 38.90, 'prato', 'Strogonoff cremoso com arroz'),
('Refrigerante Lata', 6.00, 'bebida', 'Lata 350ml'),
('Suco Natural', 8.00, 'bebida', 'Suco natural do dia'),
('Agua Mineral', 3.00, 'bebida', 'Garrafa 500ml'),
('Cerveja Long Neck', 7.00, 'bebida', 'Long neck gelada'),
('Vinho Tinto', 45.00, 'bebida', 'Garrafa de vinho tinto'),
('Caipirinha', 18.00, 'bebida', 'Caipirinha tradicional'),
('Milk Shake', 12.00, 'bebida', 'Milk shake cremoso'),
('Porcao de Fritas', 15.00, 'extra', 'Porcao crocante'),
('Farofa Extra', 8.00, 'extra', 'Farofa temperada'),
('Vinagrete', 5.00, 'extra', 'Vinagrete fresco'),
('Pao de Alho', 12.00, 'extra', 'Pao de alho assado'),
('Queijo Ralado', 4.00, 'extra', 'Queijo ralado extra'),
('Bacon Extra', 10.00, 'extra', 'Bacon crocante'),
('Azeitonas', 6.00, 'extra', 'Porcao de azeitonas'),
('Ovo Frito', 5.00, 'extra', 'Ovo frito extra')
on conflict do nothing;
