create extension if not exists pgcrypto;

create type usuario_tipo as enum ('garcom', 'gestor', 'admin');
create type mesa_status as enum ('disponivel', 'ocupada', 'manutencao', 'esperando_pagamento');
create type produto_categoria as enum ('prato', 'bebida', 'extra');
create type comanda_status as enum ('pendente', 'em_preparo', 'pronto', 'pago', 'esperando_pagamento');

create table restaurantes (
  id uuid primary key default gen_random_uuid(), nome text not null check (char_length(trim(nome)) >= 2),
  onboarding_concluido boolean not null default false, created_at timestamptz not null default now()
);
create table usuarios (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict,
  nome text not null, email text not null unique, senha text not null, tipo usuario_tipo not null, created_at timestamptz not null default now()
);
create table mesas (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict,
  numero integer not null check (numero > 0), status mesa_status not null default 'disponivel', created_at timestamptz not null default now(), unique (tenant_id, numero)
);
create table produtos (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict,
  nome text not null, preco numeric(10,2) not null check (preco >= 0), categoria produto_categoria not null,
  descricao text, disponivel boolean not null default true, created_at timestamptz not null default now()
);
create table comandas (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict,
  mesa_id bigint not null references mesas(id) on delete restrict, garcom_id bigint not null references usuarios(id) on delete restrict,
  status comanda_status not null default 'pendente', total numeric(10,2) not null default 0, numero_comanda text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, numero_comanda)
);
create table itens_comanda (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict,
  comanda_id bigint not null references comandas(id) on delete cascade, produto_id bigint not null references produtos(id) on delete restrict,
  quantidade integer not null check (quantidade > 0), preco_unitario numeric(10,2) not null check (preco_unitario >= 0),
  subtotal numeric(10,2) generated always as (quantidade * preco_unitario) stored, created_at timestamptz not null default now()
);
create table caixa_diario (
  id bigint generated by default as identity primary key, tenant_id uuid not null references restaurantes(id) on delete restrict, data date not null,
  valor_abertura numeric(10,2) not null default 0, valor_fechamento numeric(10,2), total_vendas numeric(10,2) not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, data)
);

create unique index idx_comandas_mesa_ativa on comandas(tenant_id, mesa_id) where status <> 'pago';
create index idx_usuarios_tenant on usuarios(tenant_id);
create index idx_produtos_tenant on produtos(tenant_id);
create index idx_comandas_tenant on comandas(tenant_id, created_at desc);
create index idx_itens_comanda_tenant on itens_comanda(tenant_id, comanda_id);

create or replace function set_updated_at() returns trigger as $$ begin new.updated_at = now(); return new; end; $$ language plpgsql;
create trigger trg_comandas_updated_at before update on comandas for each row execute function set_updated_at();
create trigger trg_caixa_updated_at before update on caixa_diario for each row execute function set_updated_at();
create or replace function recalcular_total_comanda() returns trigger as $$
declare alvo bigint := coalesce(new.comanda_id, old.comanda_id);
begin update comandas set total = coalesce((select sum(subtotal) from itens_comanda where comanda_id = alvo), 0) where id = alvo; return null; end;
$$ language plpgsql;
create trigger trg_itens_recalcular_total after insert or update or delete on itens_comanda for each row execute function recalcular_total_comanda();
create or replace function atualizar_status_mesa_por_comanda() returns trigger as $$
begin
  if tg_op = 'UPDATE' and old.status = new.status then return new; end if;
  if new.status = 'pago' then
    update mesas set status = 'disponivel' where id = new.mesa_id and tenant_id = new.tenant_id;
    insert into caixa_diario (tenant_id, data, total_vendas) values (new.tenant_id, current_date, new.total)
    on conflict (tenant_id, data) do update set total_vendas = caixa_diario.total_vendas + excluded.total_vendas, updated_at = now();
  elsif new.status = 'esperando_pagamento' then update mesas set status = 'esperando_pagamento' where id = new.mesa_id and tenant_id = new.tenant_id;
  else update mesas set status = 'ocupada' where id = new.mesa_id and tenant_id = new.tenant_id; end if;
  return new;
end;
$$ language plpgsql;
create trigger trg_comanda_status_mesa_insert after insert on comandas for each row execute function atualizar_status_mesa_por_comanda();
create trigger trg_comanda_status_mesa_update after update of status on comandas for each row execute function atualizar_status_mesa_por_comanda();

-- The API uses the service key; RLS prevents browser-side database access.
alter table restaurantes enable row level security;
alter table usuarios enable row level security;
alter table mesas enable row level security;
alter table produtos enable row level security;
alter table comandas enable row level security;
alter table itens_comanda enable row level security;
alter table caixa_diario enable row level security;

create or replace function criar_restaurante_onboarding(p_restaurante text, p_nome text, p_email text, p_senha_hash text)
returns table (id bigint, tenant_id uuid, nome text, email text, tipo usuario_tipo, created_at timestamptz) as $$
declare novo_tenant uuid;
begin
  insert into restaurantes (nome) values (trim(p_restaurante)) returning restaurantes.id into novo_tenant;
  return query insert into usuarios (tenant_id, nome, email, senha, tipo)
    values (novo_tenant, trim(p_nome), lower(trim(p_email)), p_senha_hash, 'admin')
    returning usuarios.id, usuarios.tenant_id, usuarios.nome, usuarios.email, usuarios.tipo, usuarios.created_at;
end;
$$ language plpgsql;
